apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordersystem-backend
  namespace: soldesk
spec:
  # Deployment나 StatefulSet이 유지할 옛날 ReplicaSet의 수를 제한한다.
  revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      app: ordersystem-backend
  template:
    metadata:
      labels:
        app: ordersystem-backend
    spec:
      containers:
        - name: ordersystem-backend
          image: 895421295243.dkr.ecr.ap-northeast-2.amazonaws.com/order-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"
          env:
            # RDS 설정은 기존 Kubernetes Secret 사용
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DB_HOST
            - name: DB_PW
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DB_PW

            # S3 Bucket 이름과 Region은 ConfigMap에서 가져온다.
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: s3-config
                  key: S3_BUCKET
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: s3-config
                  key: AWS_REGION

            # Public S3라도 업로드(PutObject)는 AWS 인증이 필요하다.
            # 실습에서는 Access Key를 Kubernetes Secret으로 주입한다.
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-s3-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-s3-secret
                  key: AWS_SECRET_ACCESS_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: ordersystem-backend-service
  namespace: soldesk
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ordersystem-backend
