name: deploy order order-backend

on:
  push:
    branches:
<<<<<<< HEAD
      - main
=======
      - dev
>>>>>>> 60e64df (ci/cd auto-12)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2
<<<<<<< HEAD

=======
      
>>>>>>> 60e64df (ci/cd auto-12)
      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install
<<<<<<< HEAD

=======
        
>>>>>>> 60e64df (ci/cd auto-12)
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
<<<<<<< HEAD
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
=======
          aws-secret-access-key:  ${{ secrets.AWS_SECRET }}
>>>>>>> 60e64df (ci/cd auto-12)
          aws-region: ap-northeast-2

      - name: update cluster infomation
        run: aws eks update-kubeconfig --name  my-cluster --region ap-northeast-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build and push docker image to ecr
        env:
          REGISTRY: 895421295243.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: order-backend
          IMAGE_TAG: latest
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
<<<<<<< HEAD
          -f ./2.ordersystem/Dockerfile ./2.ordersystem
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: restart backend deployment
        run: |
          kubectl get nodes

          kubectl get deployment ordersystem-backend \
            -n soldesk \
            -o jsonpath='{.spec.template.spec.containers[0].image}'

          echo ""

          kubectl rollout restart deployment/ordersystem-backend -n soldesk

          kubectl rollout status deployment/ordersystem-backend \
            -n soldesk \
            --timeout=300s

          kubectl get pods -n soldesk
        # kubectl apply -f ./2.ordersystem/k8s/k8s-ordersystem/depl_svc.yml
=======
          -f ./monolithic/Dockerfile ./monolithic
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: eks kubectl apply
        run: |
          kubectl rollout restart deployment ordersystem-backend -n soldesk
        # kubectl apply -f ./monolithic/k8s/k8s-ordersystem/depl_svc.yml
>>>>>>> 60e64df (ci/cd auto-12)
